name: flutter_design_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/imgs/

  fonts: 
    - family: Sematary_Medium
      fonts:
        - asset: lib/assets/font/Sematary_Medium.ttf

    - family: MADE_Okine_Sans_bold
      fonts:
        - asset: lib/assets/font/MADE_Okine_Sans_bold.otf

    - family: Satoshi_Variable
      fonts:
        - asset: lib/assets/font/Satoshi_Variable.ttf